### ISSUE TITLE
Hebrew filenames problem

### ISSUE THREAD

**Issue by Newone222** [urielha/Video.Technion#2]
Hi 
Thank you very much for that perfect solution. 
I want to use it a little. 
Now have one problem: some of files (Names of Lectures) are including Hebrew, I thought that cause an error and program stops . 
(problem didn't appear while trying lectures - named with numbers or English letters)
But  last tests showed - a problem appears because of special chars like - " ' / and other  .
Please Help

**Comment by urielha** [comment]
Hi @Newone222 
First of all please read this: https://github.com/urielha/Video.Technion#hebrew-note

Can you please specify the course url/number you are trying to download?
In addition, how do you run the script? from the cmd? or double clicking on the script file?

**Comment by Newone222** [comment]
Hi 
I mean panopto 
just try to download for example 046225 course lecture 17
Thanks a lot

**Comment by urielha** [comment]
Thanks, 
This is really weird it used to work. I will see what I can do.

**Comment by Newone222** [comment]
Wow  found strange behavior  in panopto, while tried download  from https://panoptotech.cloud.panopto.eu/Panopto/Pages/Sessions/List.aspx#folderID="cfef1428-d47c-4b5a-a44f-6544331a7e86"
most of files were empty (0kb) after  finished download.. 
If you can fix those issues it will help us !! thanks .  

good luck

**Comment by urielha** [comment]
Hi @Newone222 
Thanks for your issue I found the problem and fixed it :)
Try use this new version: https://github.com/urielha/Video.Technion/releases/tag/2.2.1

I will see about the second issue

**Comment by urielha** [comment]
Also, Try again to download the second course, I hope the filename fix has fixed it too

**Comment by urielha** [comment]
I assume the problem has been solved
